# Generated by Django 5.2.7 on 2025-11-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animal_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_peso', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Registro de peso',
                'verbose_name_plural': 'Registros de peso',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_produccion', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Registro de producción',
                'verbose_name_plural': 'Registros de producción',
                'ordering': ['-fecha'],
            },
        ),
    ]
