# Generated by Django 5.2.7 on 2025-11-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cost',
            new_name='costs_cost_batch_i_41888e_idx',
            old_name='costs_cost_batch_i_63c1ee_idx',
        ),
        migrations.RenameIndex(
            model_name='cost',
            new_name='costs_cost_tipo_c6f17c_idx',
            old_name='costs_cost_tipo_a918f7_idx',
        ),
        migrations.RenameIndex(
            model_name='cost',
            new_name='costs_cost_created_e4c036_idx',
            old_name='costs_cost_created_9b76f1_idx',
        ),
    ]
