"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from pathlib import Path
import sys

from django.core.exceptions import ImproperlyConfigured
import dj_database_url

from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Force IPv4 for DNS resolution (Supabase IPv6 workaround)
original_getaddrinfo = socket.getaddrinfo


def forced_ipv4_getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
    return original_getaddrinfo(host, port, socket.AF_INET, type, proto, flags)


socket.getaddrinfo = forced_ipv4_getaddrinfo

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-default")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tailwind",
    "theme",
    "accounts",
    "batches.apps.BatchesConfig",  # <- Cambiar esta línea
    "animals",
    "tracking",
    "costs",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# === Supabase obligatoria ===
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")
SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET", "batches")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ImproperlyConfigured("Faltan SUPABASE_URL o SUPABASE_KEY en .env")

USE_SUPABASE_STORAGE = True
DEFAULT_FILE_STORAGE = "batches.storage.SupabaseStorage"

# Base de datos: solo Supabase (Postgres)
DATABASE_URL = os.getenv("DATABASE_URL", "")
if not DATABASE_URL:
    raise ImproperlyConfigured("Falta DATABASE_URL para Supabase en .env")

db_cfg = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)

# Forzar cierre de conexiones para tests
db_cfg['OPTIONS'] = db_cfg.get('OPTIONS', {})
db_cfg['CONN_HEALTH_CHECKS'] = True

DATABASES = {
    "default": db_cfg
}

# Test configuration
if 'test' in sys.argv:
    DATABASES['default']['CONN_MAX_AGE'] = 0
    # Usar base de datos de test persistente
    DATABASES['default']['TEST'] = {
        'NAME': 'test_postgres',
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "theme" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "accounts:login"

UNFOLD = {
    "SITE_TITLE": "AgroManager",
    "SITE_HEADER": "Administración AgroManager",
    "SITE_SUBHEADER": "Panel ganadero",
    "SITE_SYMBOL": "agriculture",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Usuarios"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Inventario"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Lotes"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:batches_batch_changelist"),
                    },
                    {
                        "title": _("Animales"),
                        "icon": "pets",
                        "link": reverse_lazy("admin:animals_animal_changelist"),
                    },
                ],
            },
            {
                "title": _("Tracking"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Registros de peso"),
                        "icon": "monitor_weight",
                        "link": reverse_lazy("admin:tracking_peso_changelist"),
                    },
                    {
                        "title": _("Registros de producción"),
                        "icon": "trending_up",
                        "link": reverse_lazy("admin:tracking_produccion_changelist"),
                    },
                ],
            },
            {
                "title": _("Finanzas"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Costos"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:costs_cost_changelist"),
                    },
                ],
            },
        ],
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "batches": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

