# Generated by Django 5.2.7 on 2025-11-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_imagen_batch_batches_bat_created_56977f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('fecha_de_nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='batches.batch', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['fecha_de_nacimiento'],
            },
        ),
    ]
