# Generated by Django 5.2.7 on 2025-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-fecha_de_nacimiento'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_de_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Sexo'),
        ),
    ]
