# Generated by Django 5.2.7 on 2025-11-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código/Identificación'),
        ),
    ]
