# Generated by Django 5.2.7 on 2025-11-07 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador único del lote', max_length=50, verbose_name='Nombre del lote')),
                ('direccion', models.CharField(blank=True, help_text='Ubicación física del lote', max_length=50, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nombre'], name='batches_bat_nombre_b64ab6_idx'), models.Index(fields=['is_active'], name='batches_bat_is_acti_5fd879_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Administrador'), ('viewer', 'Visualizador')], default='viewer', max_length=30, verbose_name='Rol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_users', to='batches.batch', verbose_name='Lote')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_batches', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario-Lote',
                'verbose_name_plural': 'Usuarios-Lotes',
                'indexes': [models.Index(fields=['id_usuario', 'id_lote'], name='batches_use_id_usua_1b00e8_idx')],
                'unique_together': {('id_usuario', 'id_lote')},
            },
        ),
    ]
