# Generated by Django 5.2.7 on 2025-11-07 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbatch',
            name='id_lote',
        ),
        migrations.RemoveField(
            model_name='userbatch',
            name='id_usuario',
        ),
        migrations.RemoveIndex(
            model_name='batch',
            name='batches_bat_nombre_b64ab6_idx',
        ),
        migrations.AddField(
            model_name='batch',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['usuario', 'nombre'], name='batches_bat_usuario_6ea7bf_idx'),
        ),
        migrations.DeleteModel(
            name='UserBatch',
        ),
    ]
