# Generated by Django 5.2.7 on 2025-11-11 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_userbatch_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lotes/%Y/%m/', verbose_name='Imagen del lote'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['-created_at'], name='batches_bat_created_56977f_idx'),
        ),
    ]
