# Generated by Django 5.2.7 on 2026-02-09 19:21

import batches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_imagen_batch_batches_bat_created_56977f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=batches.models.get_batch_storage, upload_to='lotes/', verbose_name='Imagen del lote'),
        ),
    ]
